### ISSUE TITLE
support for Verifalia Api V2

### ISSUE THREAD

**Issue by softnrajkumar1994** [verifalia/verifalia-java-sdk#2]
WOULD LIKE CONTRIBUTE FOR THIS

**Comment by verifalia** [comment]
Thank you, @softnrajkumar1994 - we are already working on a first version of our Java SDK which will support most of the features of API v2.1. Once ready, we will be more than happy to accept your contribution there! Thanks

**Comment by softnrajkumar1994** [comment]
Thanks for the acknowledgement @verifalia .Waiting for it.
