### ISSUE TITLE
Setting character set on requests

### ISSUE THREAD

**Issue by apgsga-stb** [verifalia/verifalia-java-sdk#4]
When I pass an e-mail address with umlauts (such as "bär@somedomain.com") to `com.verifalia.api.emailvalidations.EmailValidationsRestClient.submit(String[], WaitingStrategy)`, I get an exception, saying "com.verifalia.api.exceptions.VerifaliaException: 400: Request charset mismatch; please check our developers documentation at https://verifalia.com/developers". I didn't find any possibility to set a character set on the client or the request. What am I supposed to do?

**Comment by apgsga-stb** [comment]
We use version 2.0.2 of the verifalia-java-sdk.

**Comment by verifalia** [comment]
Many thanks for your feedback, @apgsga-stb!
Version 2.1 of our Java SDK - which we have just released - includes a fix for the issue you have reported.

Thanks again.
